services:
  - type: web
    name: yurei-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        value: your_openai_api_key_here
    autoDeploy: true
